#!/bin/sh

#A script to quickly install packages and do setup given a new install of void linux. Should only be used by others for refrence.

#Update and install packages 
xbps-install -Suy && xbps-install -Suy
xbps-install void-repo-nonfree -y
xbps-install -y make curl neovim xorg sx firefox gcc clang lf sxiv mpv maim font-tamzen font-awesome bluez zsh pulseaudio cmake dbus lxappearance neofetch ninja nodejs opendoas pulsemixer syncthing sxhkd texlive2020-bin thunderbird xwallpaper alsa-plugins-pulseaudio alsa-utils zathura zathura-pdf-poppler youtube-dl python3 unzip wine slock rustup picom pandoc antibody libX11-devel libXinerama-devel fontconfig-devel libXft-devel libxcb-devel xst torbrowser-launcher

#Add my user to needed groups 
usermod -a -G audio,video,wheel,floppy,cdrom,optical dom
usermod -s /bin/zsh dom

#Make dirs and set variables
mkdir /home/dom/sys
mkdir /home/dom/src
echo export ZDOTDIR="/home/dom/sys/config/zsh" >> /etc/profile
cd /home/dom/sys
git clone https://github.com/MrLazerbean/config
cd /home/dom/src
git clone https://github.com/MrLazerbean/dwm
cd /home/dom
git clone https://github.com/MrLazerbean/bin
antibody bundle < /home/dom/sys/config/zsh/zsh_plugins.txt > /home/dom/sys/config/zsh/zsh_plugins.sh
sh -c 'curl -fLo /home/dom/sys/local/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
echo export PATH="$HOME/bin:/opt/texlive/2020/bin/x86_64-linux:$HOME/src/ungoogled-chromium_80.0.3987.149-2.1_linux:$PATH" >> /home/dom/sys/config/zsh/.zprofile
ln -s /mnt /home/dom
ln -s /tmp /home/dom

#Enable services 
ln -sf /etc/sv/pulseaudio /var/service
ln -sf /etc/sv/dhcpcd /var/service
ln -sf /etc/sv/dbus /var/service
ln -sf /etc/sv/alsa /var/service
ln -sf /etc/sv/bluetoothd /var/service

#Compile dwm 
cd ~/
cd src/dwm/dwm-6.2/
make install
